api_platform:
    title: 'LAN Manager API'
    description: 'API of the LAN Manager App'
    version: '1.0.0'
    show_webby: false
    oauth:
        enabled: true
        clientId: '%env(OAUTH_DISCORD_ID)%'
        clientSecret: '%env(OAUTH_DISCORD_SECRET)%'
        type: 'oauth2'
        # The oauth flow grant type.
        flow: 'authorizationCode'
        # The oauth authentication url.
        authorizationUrl: 'https://discord.com/oauth2/authorize'
        # The oauth token url.
        tokenUrl: 'https://discord.com/api/oauth2/token'
        # The oauth scopes.
        scopes:
            email: 'Allow to retrieve user email'
            identify: 'Allow to retrieve user infos'
